version: '3.5'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: my-app
    volumes:
       - .:/app
       - /app/node_modules